/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'executionLog': MotiaStream<{ executionId: string; level: 'info' | 'debug' | 'error'; message: string; step?: string; index?: number; timestamp: number }>
  }

  interface Handlers {
    'workflow.start': EventHandler<never, { topic: 'workflow.run'; data: never }>
    'workflow.run': EventHandler<never, { topic: 'input'; data: never } | { topic: 'dbFind'; data: never } | { topic: 'dbInsert'; data: never } | { topic: 'dbUpdate'; data: never } | { topic: 'delay'; data: never } | { topic: 'authMiddleware'; data: never } | { topic: 'emailSend'; data: never }>
    'saveWorkflow': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'runWorkflow': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'workflow.run'; data: never }>
    'input': EventHandler<never, { topic: 'workflow.run'; data: never }>
    'generateWorkflow': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ExecutionLogs': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'executeWorkflow': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'workflow.start'; data: never }>
    'emailSend': EventHandler<never, { topic: 'workflow.run'; data: never }>
    'delay': EventHandler<never, never>
    'dbUpdate': EventHandler<never, { topic: 'workflow.run'; data: never }>
    'dbInsert': EventHandler<never, { topic: 'workflow.run'; data: never }>
    'dbFind': EventHandler<never, { topic: 'workflow.run'; data: never }>
    'authMiddleware': EventHandler<never, { topic: 'workflow.run'; data: never }>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
  }
    
}