import type { Metadata } from "next";
import "./globals.css";
import { ClientProvider } from "@/components/ClientProvider";
import { MotiaClientProvider } from "@/components/MotiaClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <MotiaClientProvider>
          {" "}
          <ClientProvider>{children}</ClientProvider>
        </MotiaClientProvider>
      </body>
    </html>
  );
}
